export const styles = {
  header: "flex justify-between items-center h-16 px-4 border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60",
  headerLeft: "flex items-center gap-2",
  menuButton: "flex items-center justify-center w-10 h-10 rounded-md hover:bg-accent",
  logo: "flex items-center gap-2",
  logoText: "text-xl font-semibold hidden sm:block",
  searchContainer: "hidden md:flex flex-1 justify-center",
  searchWrapper: "relative flex items-center max-w-md w-full",
  searchInput: "h-10 w-full rounded-md border border-input bg-background pl-9 pr-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
  headerRight: "flex items-center gap-2",
  iconButton: "relative flex items-center justify-center w-10 h-10 rounded-md hover:bg-accent",
  notificationBadge: "absolute top-1.5 right-1.5 w-4 h-4 flex items-center justify-center text-[10px] font-bold text-white bg-red-500 rounded-full",
  profileDropdown: "relative",
  profileButton: "flex items-center justify-center cursor-pointer",
  avatar: "w-8 h-8 rounded-full border-2 border-transparent hover:border-green-500 transition-colors",
  dropdownMenu: "absolute right-0 top-full mt-2 w-64 rounded-md bg-background border shadow-lg py-2 z-50",
  dropdownHeader: "px-4 py-2",
  dropdownName: "text-sm font-medium",
  dropdownEmail: "text-xs text-muted-foreground",
  dropdownDivider: "h-px bg-border my-2",
  dropdownItem: "flex items-center gap-2 w-full text-left px-4 py-2 text-sm hover:bg-accent transition-colors"
} 